# Generated by Django 4.1.7 on 2023-04-23 03:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('67209f0b-8464-4107-ac5d-30ea7d34cb5c'), primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
